# ============================================================================
# VisaBuddy 100% Readiness Setup Script
# ============================================================================
# This script sets up everything needed for 100% app readiness
# Run this before testing on emulator
# ============================================================================

param(
    [switch]$SkipDatabase,
    [switch]$SkipSecrets
)

$ErrorActionPreference = "Stop"

Write-Host ""
Write-Host "============================================================================" -ForegroundColor Cyan
Write-Host "     VisaBuddy 100% Readiness Setup                              " -ForegroundColor Cyan
Write-Host "============================================================================" -ForegroundColor Cyan
Write-Host ""

$rootDir = Split-Path -Parent $PSScriptRoot
$backendDir = Join-Path $rootDir "apps\backend"
$frontendDir = Join-Path $rootDir "apps\frontend"
$backendEnv = Join-Path $backendDir ".env"
$frontendEnv = Join-Path $frontendDir ".env"

# ============================================================================
# Step 1: Generate Secrets
# ============================================================================
Write-Host "[1/6] Step 1: Generating secure secrets..." -ForegroundColor Yellow
Write-Host ""

# Generate JWT secrets
$JWT_SECRET = $null
$REFRESH_TOKEN_SECRET = $null

if (-not $SkipSecrets) {
    # Always generate secrets inline for reliability
    Write-Host "   Generating secure secrets..." -ForegroundColor Gray
    
    # Generate JWT secrets
    $bytes = New-Object byte[] 32
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    $rng.GetBytes($bytes)
    $JWT_SECRET = [Convert]::ToBase64String($bytes)
    
    $rng.GetBytes($bytes)
    $REFRESH_TOKEN_SECRET = [Convert]::ToBase64String($bytes)
    
    Write-Host "[OK] Generated JWT secrets" -ForegroundColor Green
} else {
    Write-Host "[SKIP] Skipping secret generation" -ForegroundColor Gray
    # Use placeholder if skipping
    $JWT_SECRET = "CHANGE_THIS_TO_A_SECURE_32_CHARACTER_OR_LONGER_SECRET"
    $REFRESH_TOKEN_SECRET = "CHANGE_THIS_TO_A_SECURE_32_CHARACTER_OR_LONGER_SECRET"
}

# ============================================================================
# Step 2: Create Backend .env
# ============================================================================
Write-Host ""
Write-Host "[2/6] Step 2: Creating backend .env file..." -ForegroundColor Yellow

if (-not (Test-Path $backendEnv)) {
    $backendEnvContent = @"
# ============================================================================
# VisaBuddy Backend Environment Configuration
# Auto-generated by setup-100-percent.ps1
# ============================================================================

# Server Configuration
NODE_ENV=development
PORT=3000

# Database Configuration (SQLite for emulator testing)
DATABASE_URL="file:./prisma/dev.db"

# JWT Authentication
JWT_SECRET=$JWT_SECRET
REFRESH_TOKEN_SECRET=$REFRESH_TOKEN_SECRET

# CORS Configuration (allows all for emulator testing)
CORS_ORIGIN=*

# Redis (Optional - using in-memory cache)
REDIS_URL=

# Storage Configuration
STORAGE_TYPE=local
LOCAL_STORAGE_PATH=uploads

# Frontend URL
FRONTEND_URL=http://localhost:19006

# Feature Flags
ENABLE_RECONCILIATION=false
ENABLE_MOCK_PAYMENTS=true

# Payment Freeze
PAYMENT_FREEZE_ENABLED=false

# Logging Configuration
LOG_LEVEL=INFO
LOG_FILE_ENABLED=false
LOG_FILE_PATH=logs
LOG_FILE_MAX_SIZE=10485760
LOG_FILE_MAX_FILES=5
"@
    
    Set-Content -Path $backendEnv -Value $backendEnvContent -Encoding UTF8
    Write-Host "[OK] Created backend .env file" -ForegroundColor Green
} else {
    Write-Host "[WARN] Backend .env already exists, skipping..." -ForegroundColor Yellow
    Write-Host "   Update JWT_SECRET and REFRESH_TOKEN_SECRET if needed" -ForegroundColor Gray
}

# ============================================================================
# Step 3: Create Frontend .env
# ============================================================================
Write-Host ""
Write-Host "[3/6] Step 3: Creating frontend .env file..." -ForegroundColor Yellow

if (-not (Test-Path $frontendEnv)) {
    $frontendEnvContent = @"
# ============================================================================
# VisaBuddy Frontend Environment Configuration
# Auto-generated by setup-100-percent.ps1
# ============================================================================

# Backend API URL (10.0.2.2 is Android emulator's localhost)
EXPO_PUBLIC_API_URL=http://10.0.2.2:3000

# Google OAuth Web Client ID (optional for testing)
EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID=YOUR_GOOGLE_WEB_CLIENT_ID_HERE
"@
    
    Set-Content -Path $frontendEnv -Value $frontendEnvContent -Encoding UTF8
    Write-Host "[OK] Created frontend .env file" -ForegroundColor Green
} else {
    Write-Host "[WARN] Frontend .env already exists, skipping..." -ForegroundColor Yellow
}

# ============================================================================
# Step 4: Setup Database
# ============================================================================
Write-Host ""
Write-Host "[4/6] Step 4: Setting up database..." -ForegroundColor Yellow

if (-not $SkipDatabase) {
    Push-Location $backendDir
    
    try {
        # Check if Prisma is installed
        if (-not (Test-Path "node_modules\.prisma")) {
            Write-Host "   Installing Prisma client..." -ForegroundColor Gray
            npm run db:generate | Out-Null
        }
        
        # Check if database exists
        $dbPath = Join-Path $backendDir "prisma\dev.db"
        if (-not (Test-Path $dbPath)) {
            Write-Host "   Creating database and running migrations..." -ForegroundColor Gray
            npm run db:migrate 2>&1 | Out-Null
            Write-Host "[OK] Database created and migrations applied" -ForegroundColor Green
        } else {
            Write-Host "[OK] Database already exists" -ForegroundColor Green
        }
    } catch {
        Write-Host "[WARN] Database setup had issues: $_" -ForegroundColor Yellow
        Write-Host "   You can run manually: cd apps\backend; npm run db:migrate" -ForegroundColor Gray
    } finally {
        Pop-Location
    }
} else {
    Write-Host "[SKIP] Skipping database setup" -ForegroundColor Gray
}

# ============================================================================
# Step 5: Verify Dependencies
# ============================================================================
Write-Host ""
Write-Host "[5/6] Step 5: Verifying dependencies..." -ForegroundColor Yellow

$missingDeps = @()

# Check Node.js
try {
    $nodeVersion = node --version
    Write-Host "   [OK] Node.js: $nodeVersion" -ForegroundColor Green
} catch {
    $missingDeps += "Node.js"
}

# Check npm
try {
    $npmVersion = npm --version
    Write-Host "   [OK] npm: $npmVersion" -ForegroundColor Green
} catch {
    $missingDeps += "npm"
}

# Check if dependencies are installed
if (Test-Path (Join-Path $backendDir "node_modules")) {
    Write-Host "   [OK] Backend dependencies installed" -ForegroundColor Green
} else {
    Write-Host "   [WARN] Backend dependencies not installed" -ForegroundColor Yellow
    Write-Host "      Run: cd apps\backend; npm install" -ForegroundColor Gray
}

if (Test-Path (Join-Path $frontendDir "node_modules")) {
    Write-Host "   [OK] Frontend dependencies installed" -ForegroundColor Green
} else {
    Write-Host "   [WARN] Frontend dependencies not installed" -ForegroundColor Yellow
    Write-Host "      Run: cd apps\frontend; npm install" -ForegroundColor Gray
}

# ============================================================================
# Step 6: Verify Environment Files
# ============================================================================
Write-Host ""
Write-Host "[6/6] Step 6: Verifying environment configuration..." -ForegroundColor Yellow

$issues = @()

# Check backend .env
if (Test-Path $backendEnv) {
    $backendContent = Get-Content $backendEnv -Raw
    if ($backendContent -notmatch "JWT_SECRET=.{32,}") {
        $issues += "Backend JWT_SECRET is missing or too short (need 32+ chars)"
    }
    if ($backendContent -notmatch "DATABASE_URL=") {
        $issues += "Backend DATABASE_URL is missing"
    }
    Write-Host "   [OK] Backend .env configured" -ForegroundColor Green
} else {
    $issues += "Backend .env file not found"
}

# Check frontend .env
if (Test-Path $frontendEnv) {
    $frontendContent = Get-Content $frontendEnv -Raw
    if ($frontendContent -notmatch "EXPO_PUBLIC_API_URL=") {
        $issues += "Frontend EXPO_PUBLIC_API_URL is missing"
    }
    Write-Host "   [OK] Frontend .env configured" -ForegroundColor Green
} else {
    $issues += "Frontend .env file not found"
}

# ============================================================================
# Summary
# ============================================================================
Write-Host ""
Write-Host "============================================================================" -ForegroundColor Cyan
Write-Host "     Setup Summary                                                 " -ForegroundColor Cyan
Write-Host "============================================================================" -ForegroundColor Cyan
Write-Host ""

if ($issues.Count -eq 0) {
    Write-Host "[OK] All checks passed! App is ready for testing." -ForegroundColor Green
    Write-Host ""
    Write-Host "Next Steps:" -ForegroundColor Yellow
    Write-Host "   1. Start backend:  cd apps\backend; npm run dev" -ForegroundColor White
    Write-Host "   2. Start Metro:    cd apps\frontend; npm run metro" -ForegroundColor White
    Write-Host "   3. Run on emulator: cd apps\frontend; npm run android" -ForegroundColor White
    Write-Host ""
} else {
    Write-Host "[WARN] Found $($issues.Count) issue(s):" -ForegroundColor Yellow
    foreach ($issue in $issues) {
        Write-Host "   - $issue" -ForegroundColor Red
    }
    Write-Host ""
    Write-Host "Fix these issues and run the script again" -ForegroundColor Cyan
}

Write-Host ""

